language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m"

script:
  - mvn clean package jacoco:report coveralls:jacoco
  - mvn -f lob-java-examples/pom.xml clean package
