name: Run tests

on: 
  push:
  pull_request:
    types: [ opened, reopened, edited ]
    branches:
      - master

jobs:
  java_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '13', '14', '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml